refactor: local binaries
Refactor some local binaries: bspc-layout; chdesk; close-all-nodes;
set-custom-screenlocker-wallpaper; set-theme; show-all-nodes.

Add help menu to some of these. Error messages and error codes. Fix
some comments.

Add a new command to chdesk script: 'chdesk init' - Start chdesk (move
current desktop to folder with desktops)

---
Changes to be committed:
      modified:   .local/bin/bspc-layout
      modified:   .local/bin/chdesk
      modified:   .local/bin/close-all-nodes
      modified:   .local/bin/set-custom-screenlocker-wallpaper
      modified:   .local/bin/set-theme
      modified:   .local/bin/show-all-nodes

diff --git a/.local/bin/bspc-layout b/.local/bin/bspc-layout
--- a/.local/bin/bspc-layout
+++ b/.local/bin/bspc-layout
@@ -8,40 +8,80 @@ BSPC_LAYOUTS_PATH=~/.config/bspwm/layouts
 BSPC_LAYOUTS_VAR=~/.local/var/bspc_layout_var
 
 
+# Show help message
+HELP_MSG()
+{
+	echo -e '\nusage: bspc-layout [command]\n'
+	echo -e 'Commands:\n'
 
-# Define the operation
-case $1 in
-	# List the layouts
-	ls | list )
+	echo '  ls | list - list the available layouts'
+	echo '  change <name> - change to the layout with the label <name>'
+	echo '  help | -h | --help - show this message'
+
+	echo -e '\n\nError codes:'
+	echo '  1: unrecognized option'
+	echo '  2: wrong number of parameters'
+	echo '  3: non-existing layout'
+}
+
+
+# Check the parameters number
+#
+# $1: Current number of parameters
+# $2: Correct number of parameters
+NUMBER_ERROR () {
+	if [[ "$1" != "$2" ]]; then
+		echo -e "\nERROR! Wrong number of parameters.\n"
+		exit 2
+	fi
+}
+
+
+# Check if a layout exists
+#
+# $1: Layout name (not the path)
+LAYOUT_EXIST()
+{
+	ls "$BSPC_LAYOUTS_PATH/$1" > /dev/null 2> /dev/null && echo true || echo false
+}
+
+
+case "$1" in
+	# List layouts
+	ls | list ) NUMBER_ERROR $# 1
 		ls $BSPC_LAYOUTS_PATH;;
 
-	# Change to the $2 layout
-	change )
-		HAS_LAYOUT='false'
+	# Change to $2 layout
+	change ) NUMBER_ERROR $# 2
+		# If the layout exists
+		if [ "$(LAYOUT_EXIST $2)" ]; then
+			# Source the files
+			source "$BSPC_FUNCTIONS_LIB"
+			source "${BSPC_LAYOUTS_PATH}/$2"
 
-		for loop in $(ls $BSPC_LAYOUTS_PATH); do
-			if [ $2 == $loop ]; then
-				# Change the 'HAS_LAYOUT' variable
-				HAS_LAYOUT='true'
+			# Execute the change
+			UPDATE_LEAFS
+			LAYOUT_CHANGE
 
-				# Source the files
-				source $BSPC_FUNCTIONS_LIB
-				source ${BSPC_LAYOUTS_PATH}/$2
-
-				# Execute the change
-				UPDATE_LEAFS
-				LAYOUT_CHANGE
-
-				break
-			fi
-
-		done
-
-		# If there aren't the $2 layout
-		if [ "$HAS_LAYOUT" == 'false' ]; then
-			echo "There aren't this layout. Use 'bspc-layout ls' to view the available layouts."
+		# If there isn't the $2 layout
+		else
+			echo "There aren't this layout! Use 'bspc-layout ls' to view the available layouts."
+			exit 3
 		fi
 
+		;;
+
+	# Show help message
+	help | -h | --help ) NUMBER_ERROR $# 1
+		HELP_MSG;;
+
+	# Error because there are no parameters
+	"" ) NUMBER_ERROR $# 1;;
+
+	# If there is no compatible option
+	* )
+		echo "Command: 'bspc-layout'; unrecognized option: '$1'"
+		exit 1
 		;;
 esac
 
diff --git a/.local/bin/chdesk b/.local/bin/chdesk
--- a/.local/bin/chdesk
+++ b/.local/bin/chdesk
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# OBS.: This is experimental. Yopu need to delete the '~/Desktop' directory
+# OBS.: This is experimental. You need to delete the '~/Desktop' directory
 
 
 set -e
@@ -8,94 +8,158 @@ set -e
 DESKDIR="$HOME/.Desktops"
 
 
-# Show error message
-HELPCHDESK () {
-	echo -e '\nusage: chdesk command\n'
+# Show help message
+HELP_MSG()
+{
+	echo -e '\nusage: chdesk [command]\n'
 	echo -e 'Commands:\n'
 
-	echo 'list | ls - lists the avaliable desktops'
-	echo 'help - show this mensage'
-	echo 'add | make <name> - create a new desktop with the label name'
-	echo 'dell | rm | remove <name> - telete a desktop "name"'
-	echo 'change <name> - change to the desktop with the label <name>';
+	echo '  init - Start chdesk (move current desktop to folder with desktops)'
+	echo '  list | ls - list the available desktops'
+	echo '  add | make <name> - create a new desktop with the label <name>'
+	echo '  cp | copy <src> <dest> - copy the <src> desktop to a new one named <name>'
+	echo '  rm | remove | dell <name> - delete a desktop <name>'
+	echo '  change <name> - change to the desktop with the label <name>'
+	echo '  help | -h | --help - show this message'
+
+	echo -e '\n\nError codes:'
+	echo '  1: unrecognized option'
+	echo '  2: wrong number of parameters'
+	echo '  3: trying to create an existing desktop'
+	echo '  4: non-existing desktop'
+	echo '  5: trying to start chdesk, but it has already been started'
 }
 
 
 # Check the parameters number
-NUMBERERROR () {
+#
+# $1: Current number of parameters
+# $2: Correct number of parameters
+NUMBER_ERROR()
+{
 	if [[ "$1" != "$2" ]]; then
-		exec echo -e "\nERROR! There are not a correct number of parameters.\n"
+		echo -e "\nERROR! Wrong number of parameters.\n"
+		exit 2
 	fi
 }
 
 
-case $1 in
+# Check if a Desktop exists
+#
+# $1: Desktop name (not the path)
+DESKTOP_EXIST()
+{
+	ls "$DESKDIR/$1" > /dev/null 2> /dev/null && echo true || echo false
+}
+
+
+case "$1" in
+	# Init chdesk
+	init) NUMBER_ERROR $# 1
+		# Does not init if it has already been started
+		ls "$DESKDIR" > /dev/null 2> /dev/null && \
+			{
+				echo -e '\nChdesk has already been started!\n'
+				exit 5
+			}
+
+		# Directory with desktops
+		mkdir "$DESKDIR"
+
+		# If the current '~/Desktop' is a link, switch by a folder
+		if [[ -L ~/Desktop ]]; then
+			rm ~/Desktop
+			mkdir ~/Desktop
+		fi
+
+		# Move current desktop and change to it
+		mv ~/Desktop "$DESKDIR/Desktop"
+		$0 change Desktop
+		;;
 
 	# List all "Desktops"
-	list | ls ) 	NUMBERERROR $# 1
+	list | ls ) NUMBER_ERROR $# 1
 		ls "$DESKDIR"
 		declare -i VALOR=$(ls -l ~/Desktop | fgrep -o '/' | wc -l)
 		VALOR=${VALOR}+1
 
-		echo -e "\nActive: `ls -l ~/Desktop | cut -d'/' -f${VALOR}`";;
-
+		echo -e "\nActive: `ls -l ~/Desktop | cut -d'/' -f${VALOR}`"
+		;;
 
 	# Create a new "Desktop"
-	add | make ) 	NUMBERERROR $# 2
-		for loop in $(ls "${DESKDIR}"); do
-			if [[ $loop == $2 ]]; then
-				exec echo -e '\nThis Desktop already exists! Choose other name.\n'
-			fi
-		done
-		mkdir -p "${DESKDIR}/$2";;
+	add | make ) NUMBER_ERROR $# 2
+		# Does not create if it already exists
+		if [[ "$(DESKTOP_EXIST $2)" == 'true' ]]; then
+			echo -e '\nThis Desktop already exists! Choose other name.\n'
+			exit 3
 
+		# Creates the new Desktop
+		else
+			mkdir -p "${DESKDIR}/$2"
+		fi
+		;;
 
 	# Copy a existing "Desktop"
-	cp | copy )	NUMBERERROR $# 3
-		cp -r "${DESKDIR}/$2"  "${DESKDIR}/$3";;
-
-
-	# Remove a existing "Desktop"
-	rm | remove | dell )	NUMBERERROR $# 2
-		rm -r "${DESKDIR}/$2";;
-
-
-	# Change to the "Desktop"
-	change )	NUMBERERROR $# 2
-		var1='no'
-		for loop in $(ls $DESKDIR); do
-			if [[ $2 == $loop ]]; then
-				var1='yes'
-			fi
-		done
-
-		if [[ $var1 == 'no' ]]; then
-			exec echo -e "\nThere aren't this desktop\n"
+	cp | copy ) NUMBER_ERROR $# 3
+		# Does not copy if the Desktop does not exist
+		if [[ "$(DESKTOP_EXIST $2)" == 'false' ]]; then
+			echo -e '\nThis Desktop does not exists!\n'
+			exit 4
 		fi
 
+		# Does not copy if the destination already exists
+		if [[ "$(DESKTOP_EXIST $3)" == 'true' ]]; then
+			echo -e '\nThe destination Desktop already exists! Choose other name.\n'
+			exit 3
+		fi
+
+		# Copies the Desktop
+		cp -r "${DESKDIR}/$2"  "${DESKDIR}/$3"
+		;;
+
+	# Remove a existing "Desktop"
+	rm | remove | dell ) NUMBER_ERROR $# 2
+		# Does not delete if the Desktop does not exist
+		if [[ "$(DESKTOP_EXIST $2)" == 'false' ]]; then
+			echo -e '\nThis Desktop does not exists!\n'
+			exit 4
+		fi
+
+		# Deletes
+		rm -r "${DESKDIR}/$2"
+		;;
+
+	# Change to the "Desktop"
+	change ) NUMBER_ERROR $# 2
+		# Does not change if it does not exists
+		if [[ "$(DESKTOP_EXIST $2)" == 'false' ]]; then
+			echo -e '\nThis Desktop does not exists!\n'
+			exit 4
+		fi
+
+		# Changes the Desktop
 		ln -dsfT "${DESKDIR}/$2" ~/Desktop
-		
-		if [ "1$XDG_CURRENT_DESKTOP" == '1XFCE' ]; then
+
+		# Restarts the desktop (if in xfce)
+		if [ "$XDG_CURRENT_DESKTOP" == 'XFCE' ]; then
 			xfdesktop -Q
 			xfdesktop -R &
 		fi
 		;;
 
+	# Show help message
+	help | -h | --help ) NUMBER_ERROR $# 1
+		HELP_MSG;;
 
-	# Show HELP message
-	help | h | --help ) NUMBERERROR $# 1
-		HELPCHDESK;;
+	# Error because there are no parameters
+	"" ) NUMBER_ERROR $# 1;;
 
-
-	# If there is no compatible opition
-	* ) 	echo -e "\nThere aren't this opition\n";;
-
-	esac
-
-
-# Unset variables
-unset DESKDIR
-unset HELPCHDESK
+	# If there is no compatible option
+	* )
+		echo "Command: 'chdesk'; unrecognized option: '$1'"
+		exit 1
+		;;
+esac
 
 
 # vim: nobackup
diff --git a/.local/bin/set-theme b/.local/bin/set-theme
--- a/.local/bin/set-theme
+++ b/.local/bin/set-theme
@@ -1,31 +1,62 @@
 #!/bin/bash
 
 
+# Show help message
+HELP_MSG()
+{
+	echo -e '\nusage: set-theme [command] <parameters>\n'
+	echo -e 'Commands:\n'
+
+	echo '  -g | --gtk <name> - Set the current GTK theme to <name>'
+	echo '  -i | --icon <name> - Set the current icon theme to <name>'
+	echo '  -c | --cursor <name> - Set the current cursor theme to <name>'
+	echo '  --fix-cursor - Fix the cursor theme (some login manager can change it)'
+	echo '  help | -h | --help - show this message'
+
+	echo -e '\n\nError codes:'
+	echo '  1: unrecognized option'
+	echo '  2: wrong number of parameters'
+}
+
+
+# Check the parameters number
+#
+# $1: Current number of parameters
+# $2: Correct number of parameters
+NUMBER_ERROR () {
+	if [[ "$1" != "$2" ]]; then
+		echo -e "\nERROR! Wrong number of parameters.\n"
+		exit 2
+	fi
+}
+
+
 # Change a file attribute
+#
+# $1: file path
+# $2: Attribute pathern
+# $3: Attribute value
 CHANGE_FILE_ATTRIBUTE()
 {
-	# $1: file path
-	# $2: Attribute pathern
-	# $3: Attribute Value
-
 	# Change the file attribute
 	sed -i s/"${2}.*"/"${2}=${3}"/ "$1"
 }
 
 
 # Get a file attribute
+#
+# $1: File path
+# $2: Attribute name
 GET_FILE_ATTRIBUTE()
 {
-	# $1: File path
-	# $2: Attribute name
-
 	cat "$1" | awk "/$2/" | sed -n 1p | sed 's/.*=//g'
 }
 
 
 # Main code
 case "$1" in
-	'-g' | '--gtk' )
+	# Set GTK theme
+	'-g' | '--gtk' ) NUMBER_ERROR $# 2
 		# GTK 2
 		CHANGE_FILE_ATTRIBUTE ~/.gtkrc-2.0 'gtk-theme-name' "\"$2\""
 
@@ -36,7 +67,8 @@ case "$1" in
 		gsettings set org.gnome.desktop.interface gtk-theme "$2"
 		;;
 
-	'-i' | '--icon')
+	# Set icon theme
+	'-i' | '--icon') NUMBER_ERROR $# 2
 		# GTK 2
 		CHANGE_FILE_ATTRIBUTE ~/.gtkrc-2.0 'gtk-icon-theme-name' "\"$2\""
 
@@ -50,7 +82,8 @@ case "$1" in
 		gsettings set org.gnome.desktop.interface icon-theme "$2"
 		;;
 
-	'-c' | '--cursor' )
+	# Set cursor theme
+	'-c' | '--cursor' ) NUMBER_ERROR $# 2
 		# GTK 2
 		CHANGE_FILE_ATTRIBUTE ~/.gtkrc-2.0 'gtk-cursor-theme-name' "\"$2\""
 
@@ -71,10 +104,25 @@ case "$1" in
 		xsetroot -cursor_name left_ptr
 		;;
 
-	'--fix-cursor' )
+	# Fix cursor theme. Some login managers can change the cursor theme.
+	# This option is needed to restore the cursor to the correct one.
+	'--fix-cursor' ) NUMBER_ERROR $# 1
 		# X server
 		echo "Xcursor.theme: $(GET_FILE_ATTRIBUTE ~/.config/gtk-3.0/settings.ini gtk-cursor-theme-name)" | xrdb
 		xsetroot -cursor_name left_ptr
+		;;
+
+	# Show help message
+	help | -h | --help ) NUMBER_ERROR $# 1
+		HELP_MSG;;
+
+	# Error because there are no parameters
+	"" ) NUMBER_ERROR $# 1;;
+
+	# If there is no compatible option
+	* )
+		echo "Command: 'bspc-layout'; unrecognized option: '$1'"
+		exit 1
 		;;
 esac
 
